name: 🐞 Bug Report
description: Report a bug in Core, Adapters, or Modules
title: "[Bug] : "
type: Bug
labels: ["status: Waiting Triage"]

body:

  - type: dropdown
    id: platform
    attributes:
      label: "Platform:"
      description: Which part of FireHub is affected?
      options:
        - Core Foundation
        - Core Professional
        - Core Enterprise
        - UI Adapter
        - Infrastructure Adapter
        - Capability Module
        - Adapter Module
        - Skeleton
        - ...other platform
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: "Platform version:"
      description: Which version is the affected platform?
      placeholder: "example: v4.3.24"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: "PHP version:"
      description: Which PHP version are you using in your environment?
      placeholder: "example: 8.5.0"
    validations:
      required: true

  - type: checkboxes
    id: exist
    attributes:
      label: Have you searched the existing issues?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: Yes, I have searched the existing issues
          required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS:
        - Web Server / CLI:
        - Browser (if applicable):
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links, references, screenshots, logs, stack traces, or any other relevant info that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false