name: Code Coverage

on:
  workflow_call:
    inputs:
      phpVersion:
        type: string
        required: true
      phpExtensions:
        type: string
        required: true
      tools:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  run:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          extensions: ${{ inputs.phpExtensions }}
          tools: ${{ inputs.tools }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      # -------------------------
      # UNIT TESTS
      # -------------------------
      - name: Run Unit Tests
        run: |
          phpunit \
            --testsuite unit \
            --coverage-clover=coverage-unit.xml \
            --log-junit junit-unit.xml

      - name: Upload Unit Coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage-unit.xml
          flags: unit
          name: unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}

      # -------------------------
      # INTEGRATION TESTS
      # -------------------------
      - name: Run Integration Tests
        run: |
          phpunit \
            --testsuite integration \
            --coverage-clover=coverage-integration.xml \
            --log-junit junit-integration.xml

      - name: Upload Integration Coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage-integration.xml
          flags: integration
          name: integration-tests
          token: ${{ secrets.CODECOV_TOKEN }}

      # -------------------------
      # SMOKE TESTS
      # -------------------------
      - name: Run Smoke Tests
        run: |
          phpunit \
            --testsuite smoke \
            --coverage-clover=coverage-smoke.xml \
            --log-junit junit-smoke.xml

      - name: Upload Smoke Coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage-smoke.xml
          flags: smoke
          name: smoke-tests
          token: ${{ secrets.CODECOV_TOKEN }}

      # -------------------------
      # TEST RESULTS (ALL)
      # -------------------------
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}