name: Code Coverage

on:
  workflow_call:
    inputs:
      phpVersion:
        type: string
        required: true
      phpExtensions:
        type: string
        required: true
      tools:
        type: string
        required: true
      suites:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  run:
    name: Code Coverage (${{ matrix.suite }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJson(inputs.suites) }}
    steps:

      # -------------------------
      # CHECKOUT & INSTALL
      # -------------------------
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          extensions: ${{ inputs.phpExtensions }}
          tools: ${{ inputs.tools }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      # -------------------------
      # RUN TESTS PER SUITE
      # -------------------------
      - name: Run PHPUnit (${{ matrix.suite }})
        run: |
          phpunit \
            --testsuite ${{ matrix.suite }} \
            --coverage-clover=coverage-${{ matrix.suite }}.xml \
            --log-junit junit-${{ matrix.suite }}.xml

      # -------------------------
      # Upload to Codecov
      # -------------------------
      - name: Upload Unit Coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage-${{ matrix.suite }}.xml
          flags: ${{ matrix.suite }}
          name: ${{ matrix.suite }}-tests
          token: ${{ secrets.CODECOV_TOKEN }}

      # -------------------------
      # TEST RESULTS (ALL)
      # -------------------------
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}